### ISSUE TITLE
EPIC: TypeSystem

### ISSUE THREAD

**Issue by pskfyi** [pskfyi/js-type-systems#64]
- [ ] Define `class TypeSystem`
  - [X] name
  - [ ] raising `Type.is()` to `TypeSystem.is[type]()` and `TypeSystem.is${type}()` helpers
  - [ ] raising `Type.new()` to `TypeSystem.new[type]()` and `TypeSystem.new${type}()` helpers
  - [ ] raising `Type.castTo()` to `TypeSystem.castTo[type]()` and `TypeSystem.to${type}`
  - [ ] raising `Type.canCastTo()` to `TypeSystem.canCastTo[type]`
  - [ ] raising `Type.primitive` to `TypeSystem.primitives` getter
  - [ ] serialize & deserialize
  - [ ] constant
  - [ ] values
- [ ] Example valid and invalid type defs
- [ ] 100% coverage
- [ ] Documentation
